apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      role: redcnn
  template:
    metadata:
      labels:
        role: redcnn
    spec:
      containers:
        - name: cnn-frontend
          image: registry-1.docker.io/if722399/cnn-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
      imagePullSecrets:
        - name: pneumonia_detector

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 8501
  selector:
    role: redcnn

